[project]
name = "pdf-form-builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
license = "GNU AFFERO GPL 3.0"
license-files = ["LICENSE"]
dependencies = [
    "pymupdf>=1.26.7",
]
